[package]
name = "oxidized-perl"
version = "0.1.0"
edition = "2024"
license = "MIT"
build = "build.rs"

[[bin]]
name = "perl"
path = "src/main.rs"

[dependencies]
fancy-regex = "0.18.0"
indexmap = "2"
libc = "0.2"
regex = "1"

[build-dependencies]
cc = "1"

[profile.release]
strip = true
lto = true
